- README.md
- cmd/finch-daemon/main.go
- updates documentation to be more accurate
- updates casing for socketAddr to match other CLI parameters
> fix: doc nits and parameter casing

- .github/workflows/release-automation.yaml
- release-please-config.json
- set release version to 0.9.0
- add go to release instance to fix go-license failures
> fix: Set release version to 0.9.0

- README.md
Clarify language about systemd service in README
> fix: README changes re: systemd setup

- release-please-config.json
Revert hardcoded commit version from #56 
> chore: Revert to release-please versioning

- .github/workflows/ci.yaml
- Makefile
- README.md
- e2e/e2e_test.go
Updated the finch-daemon common Makefile target name to match the targets defined in finch cli. 
> refactor: Update Makefile target names to match finch cli

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
Add Support for Extra Hosts to be able to add hosts
> feat: Add Support for Extra Hosts

- go.mod
- go.sum
> fix: Update go mod to fix CVE-2024-45338

- api/handlers/container/container.go
- api/handlers/container/kill.go
- api/handlers/container/kill_test.go
- e2e/e2e_test.go
- e2e/tests/container_kill.go
- internal/backend/container.go
- internal/service/container/kill.go
- internal/service/container/kill_test.go
- mocks/mocks_backend/nerdctlcontainersvc.go
- mocks/mocks_container/containersvc.go
- mocks/mocks_statsutil/statsutil.go
Add container kill API support to finch daemon
Unit test and E2E test
> feat: Add container kill API

- e2e/e2e_test.go
- resolving TODO comment as this will be useful for finch-daemon into finch integration
> test: allow overriding the test subject binary

- Makefile
- api/handlers/container/container.go
- api/handlers/container/pause.go
- api/handlers/container/pause_test.go
- e2e/e2e_test.go
- e2e/tests/container_pause.go
- internal/backend/container.go
- internal/service/container/pause.go
- internal/service/container/pause_test.go
- mocks/mocks_backend/nerdctlcontainersvc.go
- mocks/mocks_container/containersvc.go
> feat: Add pause container support

- api/handlers/container/container.go
- api/handlers/container/unpause.go
- api/handlers/container/unpause_test.go
- e2e/e2e_test.go
- e2e/tests/container_unpause.go
- internal/backend/container.go
- internal/service/container/unpause.go
- internal/service/container/unpause_test.go
- mocks/mocks_backend/nerdctlcontainersvc.go
- mocks/mocks_container/containersvc.go
> feat: Add unpause container support

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add OomKillDisabled, NetworkDisabled and MACAddress option

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add Cpu options and missing tests to cidfile option

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add Blkio related options

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add VolumesFrom, Tmpfs and UTSMode option

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add PidMode, Ipcmode and GroupAdd options

- api/handlers/container/container.go
- api/handlers/container/stop.go
- e2e/tests/container_restart.go
- e2e/tests/container_stop.go
- internal/backend/container.go
- internal/service/container/restart.go
- internal/service/container/restart_test.go
- internal/service/container/stop.go
- internal/service/container/stop_test.go
- mocks/mocks_backend/nerdctlcontainersvc.go
- mocks/mocks_container/containersvc.go
Needs https://github.com/containerd/nerdctl/pull/3892 to be merged and released upstream
> feat: add signal option to containerStop

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add ShmSize, Sysctl and Runtime option

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
> feat: Add ReadonlyRootfs option

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/tests/container_create.go
Adds support for annotations 
- set meta data on a container (passed through to the OCI runtime)
> feat: Add annotations option

- api/handlers/container/create.go
- api/handlers/container/create_test.go
- api/types/container_types.go
- e2e/e2e_test.go
- e2e/tests/container_create.go
This PR adds devices option to the create command.  allowing users to make specific host devices available within a container
**Description of changes:*
- added option
- unit tests 
- integration tests
> feat: Add devices option

- internal/service/network/driver/bridge.go
Prior to nerdctl v2.0.0, networks created with or without namespace have their network configs places in the default CNI network config dir `/etc/cni/net.d/` path
```bash
dev-dsk-sbora-2c-038007b3 % DOCKER_HOST=unix:///run/finch.sock docker network create test_net
27bf89a9452003ad0d4f1a234d3df84fc56fbb2db9456932e1124f7c4708e696
(25-06-03 21:23:21) <0> [~/finch-daemon]
dev-dsk-sbora-2c-038007b3 % sudo nerdctl network ls |grep test_net
27bf89a94520    test_net    /etc/cni/net.d/nerdctl-test_net.conflist
```
After nerdctl v2.0.0 upgrade in finch-daemon v0.13.0, networks are now created in their respective namespaced directory
```bash
(25-06-03 21:25:46) <0> [~/finch-daemon]
dev-dsk-sbora-2c-038007b3 % DOCKER_HOST=unix:///run/finch.sock docker …
```
> fix: handleNetworkLabels failing after nerdctl v2.0.0 upgrade

- internal/service/container/inspect.go
- internal/service/container/inspect_test.go
- internal/service/container/list.go
1. Container Inspect Test
2.  Container List Test
> fix: restore update network settings for dockercompat

- .github/workflows/samcli-direct.yaml
- .github/workflows/samcli-vm.yaml
- scripts/samcli-vm/check-test-results.sh
*Description of changes:* Minor fixes for SAMcli automation workflows, including better failure handling and explicit role duration.
> ci: samcli automation fixes
