Makefile

Strip the debug info by default to reduce the output binary size.
Also added the "clean" build target.

chore: strip debug info and add the clean build target

---

cmd/finch-daemon/main.go
docs/debug.md

- Adds a new `debug-addr` CLI parameter which allows setting of a listener address for pprof usage
- Adds documentation for how to debug finch-daemon, including how to use pprof
I wasn't sure how to tag this PR, between "chore" (because this doesn't change finch-daemon's end-user experience), and "feat" (because it does add a new CLI parameter). Input appreciated 😁

chore: add pprof and debug docs

---

cmd/finch-daemon/main.go
cmd/finch-daemon/router_utils.go
cmd/finch-daemon/router_utils_test.go
docs/finch-daemon-config.md
go.mod
go.sum

Issue #, if available: 
This feature adds capability to read configurations from nerdctl toml file and nerdctl supported env variables and configure accordingly. 
Functional test are added for functions to check logical and functional correctness.

feat: Add support for nerdctl config and default variables

---

.github/workflows/release-automation.yaml
Makefile
scripts/create-releases.sh
scripts/verify-release-artifacts.sh

- verified o/p of finch daemon binaries from [fork release](https://github.com/coderbirju/finch-daemon/releases/tag/v0.9.1)
- dynamic 
`$ ldd ./finch-daemon
linux-vdso.so.1 (0x00007ffc112ba000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000778e82c00000)
/lib64/ld-linux-x86-64.so.2 (0x0000778e82e43000)`
`$ file ./finc-daemon`
`./finch-daemon: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3db17231b58a26bfc842a2f4101034c909cee7e8, for GNU/Linux 3.2.0, with debug_info, not stripped`
- static
`$ ldd ./finch-daemon
not a dynamic executable
`
`$ file ./finc-daemon`
`./finch-daemon: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), …

fix: Add static binaries to release

---

release-please-config.json

Fixes an issue with release please that made it bump the patch version instead of minor version on new feature commits

fix: Remove bump-patch-for-minor-pre-major

---

cmd/finch-daemon/main.go

Add support for pidfile.
1. Start finch daemon with pidfile option and check if file is created.

feat: Add support for pidfile

---

.github/workflows/release-automation.yaml
scripts/create-releases.sh
scripts/verify-release-artifacts.sh

Note: Cancelled a previous pr due to a broken state caused during a override.
https://github.com/runfinch/finch-daemon/pull/97
Description of changes:
Add support for arm64 build and release
Testing done:
1.Create a release and check the workflow
2. Download each version and run finch --version for:
a. Dynamic and Static Arm64
b. Dynamic and Static Amd64 
I've reviewed the guidance in CONTRIBUTING.md
License Acceptance

fix: Add arm64 build and release

---

internal/service/network/driver/bridge.go

Addressing a comment from the PR https://github.com/runfinch/finch-daemon/pull/69#discussion_r1810770866
If the option to configure custom bridge name is set, finch-daemon will try to set the bridge name by updating the CNI conflist of the network. However, on failure, it will simply return a warning instead of failing. This change returns an explicit error if an error is encountered. 
The created Network will be removed as part of a defer cleanup in Create.

fix: return an error if custom bridge name is not set successfully

---

cmd/finch-daemon/main.go
docs/sample-service-files/finch-socket-activation.service
docs/sample-service-files/finch-socket-activation.socket
go.mod
go.sum

fix: Pidfile handling and socket docs
1. Pidfile handling in daemon needs to handle concurrent access case and defer should be only be called if the file was created by the same daemon.
2. Updated the socket docs. 

fix: Pidfile handling and socket docs

---

e2e/tests/network_create.go

Adds e2e test for enable_icc option
`sudo make test-e2e`

test: add e2e test for com.docker.network.bridge.enable_icc option

---

.github/workflows/release-automation.yaml
scripts/create-releases.sh
scripts/verify-release-artifacts.sh

Missing e2e tests on ARM.
This change reverts https://github.com/runfinch/finch-daemon/pull/99 until e2e tests can be ran on ARM runners in CI. 
N/A

revert: "fix: Add arm64 build and release (#99)"

---

api/handlers/container/container.go
api/handlers/container/container_test.go
api/handlers/container/inspect.go
api/handlers/container/inspect_test.go
api/types/container_types.go
e2e/e2e_test.go
e2e/tests/container_inspect.go
internal/backend/container.go
internal/service/container/inspect.go
internal/service/container/inspect_test.go
internal/service/container/list.go
internal/service/container/list_test.go
mocks/mocks_backend/nerdctlcontainersvc.go
mocks/mocks_container/containersvc.go

Adds SizeRW and SizeRootFs options to inspect response
Inspect response without size option passed
```
{
"Id": "842c7a142d2249f0c25e654a10e4fb10ac5ae2c7fa6cd6fa8d94dbc5fd44ac2c",
"Created": "2025-02-10T19:43:07.960689829Z",
"Path": "sleep",
"Args": [],
"State": { ...},
"Image": "docker.io/library/ubuntu:latest",
"ResolvConfPath": "/var/lib/nerdctl/1935db59/containers/finch/842c7a142d2249f0c25e654a10e4fb10ac5ae2c7fa6cd6fa8d94dbc5fd44ac2c/resolv.conf",
"HostnamePath": "/var/lib/nerdctl/1935db59/containers/finch/842c7a142d2249f0c25e654a10e4fb10ac5ae2c7fa6cd6fa8d94dbc5fd44ac2c/hostname",
"LogPath": "/var/lib/nerdctl/1935db59/containers/finch/842c7a142d2249f0c25e654a10e4fb10ac5ae2c7fa6cd6fa8d94dbc5fd44ac2c/842c7a142d2249f0c25e654a10e4fb10ac5ae2c7fa6cd6fa8d94dbc5fd44ac2c-j …
```

feat: Update container inspect with size option

---

api/handlers/container/container.go
api/handlers/container/container_test.go
api/handlers/container/restart.go
api/handlers/container/restart_test.go
api/handlers/container/start.go
api/handlers/container/start_test.go
internal/backend/container.go
internal/service/container/restart.go
internal/service/container/restart_test.go
internal/service/container/start.go
internal/service/container/start_test.go
mocks/mocks_backend/nerdctlcontainersvc.go
mocks/mocks_container/containersvc.go

feat: add detachKeys option to container start

---

.github/workflows/ci.yaml

This change bumps the containerd matrix for 1.7.26 and 2.0.2 containerd releases.
Green checks says it all

chore(ci): bump containerd [1.7.27, 2.0.4] matrix

---

api/handlers/container/container.go
api/handlers/container/wait.go
e2e/e2e_test.go
e2e/tests/container_wait.go
internal/backend/container.go
internal/service/container/wait.go
internal/service/container/wait_test.go
mocks/mocks_backend/nerdctlcontainersvc.go
mocks/mocks_container/containersvc.go

- Use nerdctl's implementation of [container wait](https://github.com/containerd/nerdctl/blob/main/pkg/cmd/container/wait.go) instead of doing it on our own
- add some unit tests 

fix: refactor wait API

---

api/handlers/container/list.go
api/handlers/container/list_test.go
api/handlers/system/events.go
api/handlers/system/events_test.go
api/types/filter_types.go
e2e/tests/container_list.go

This commit adds filter types and parsing capabilities to easily fetch these for our containers list and events APIs.
Parsing logic has been ported over from https://github.com/moby/moby/blob/5f0d6731eb015c8e46b2ae9bb1803d005f2513be/api/types/filters/parse.go

fix: Refactor filters parsing

---

.github/workflows/ci.yaml
.github/workflows/release-automation.yaml
go.mod

Current release automation workflow is failing during the `make licenses` step.
Investigation has shown that the golang version in the runner is still 1.22.7 and similar issue reported upstream has pointed to golang update as the resolution.

chore: update golang 1.23 for release automation runner

---

Makefile
e2e/tests/container_restart.go
setup-test-env.sh

As seen in these error logs where the tests are being run from a macOS host system, there are issues which cause date parsing to not work uniformly across platforms. These changes make the way we're extracting the tests more readable and consistent in such scenarios, without breaking the existing functionality on Linux
Example test failure (source, [will expire](https://github.com/runfinch/finch/actions/runs/14136677910/job/39609957869?pr=1181)):
```
Finch Daemon Functional test restart a container should start and restart the container
/Users/ec2-user/ar/_work/finch/finch/deps/finch-core/src/finch-daemon/e2e/tests/container_restart.go:40
localhost:56438/alpine:latest:                                                    resolved …
```

test: improve date parsing robustness

---

api/handlers/builder/build.go
api/handlers/builder/build_test.go

feat: add additional options to image build

---

e2e/util/option_wrapper.go

Issue #, if available: #223
Fix for issue described here: https://github.com/runfinch/finch-daemon/issues/223. Thanks @chews93319 for the extra pair of eyes and deep dive, I couldn't see this issue at first from being "too close" to the code. I'm guessing I originally wrote the code the way I did because of the standard go idiom of reassigning back to the appended variable. In this case, that's wrong.
The reason this manifests as flakes is totally down to go/Ginkgo test parallelism and ordering. Whenever the "failure" test runs after the "success" test, the tests will pass because the failure test is still failing, just not for the right reason. There might be other cases which cause state to reset between parallel tests, but that's the most obvious condition.
- Recreated the issue …

test(fix): don't override function variable

---

.github/workflows/release-automation.yaml

Release automation currently fails due to GitHub Actions retirement of Ubuntu-20 runners.
This change updates the release automation runners to Ubuntu-22.04
N/A

ci: update release github actions runners to ubuntu-22.04

---

api/handlers/container/create.go
api/handlers/container/create_test.go
api/types/container_types.go
e2e/tests/container_create.go

Adds cgroupsns option to container create. this allows users to control the cgroup namespace a container uses
- added option
- unit tests 
- integration tests

feat: Add cgroupnsmode option

---

e2e/tests/container_create.go

This PR adds a fix to the blkiodevice e2e tests which fail in finch CI because it runs within a VM space and the test creates resources in the host.

fix: Update blkio tests to be compatible with finch CI

---

e2e/tests/container_create.go

skipping blkio test on mac/windows finch vm setups
```
finch Daemon Functional test create container [It] should create container with specified blkio settings options
/Users/shubhum/Documents/WorkPackages/finch-daemon/e2e/tests/container_create.go:800
[SKIPPED] Blkio settings are only supported on Linux
```

fix: skip blkio test in vm

---

.github/workflows/ci.yaml

We are seeing multiple lint failures in the CI as github rolls out newer version of its [ubuntu-24.04 images](https://github.com/actions/runner-images?tab=readme-ov-file#available-images)
Updating the GOLANGCI_LINT_VERSION to the latest 1.64.8 seems to be working. (Verified that the runner image version is Version: 20250609.1.0)
We should revisit the lint action version as we are 2 versions behind at the moment (v8 vs v6)
However that could be a bigger change as [golangci-lint-action beyond 6  supports golangci version > 2 only](https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#compatibility)
This PR will unblock all the new PRs
By submitting this pull request, I confirm that my contribution is made under …

chore: update golangci_lint version

---

scripts/verify-release-artifacts.sh

fix release artifact checks to take docker-credential-finch binary

fix: verify release artifact docker-credential-finch

---

e2e/tests/container_stats.go

Improve  container stat test to be more deterministic by waiting for container to be in a running state before checking the stats.

fix: container stat test flakiness

---

.github/workflows/ci.yaml
setup-test-env.sh

Adding capability to run e2e test against different versions of nerdctl cli. This is to ensure we have compatibility with older versions of nerdctl cli

ci: Run e2e against different  nerdctl cli versions

---

api/handlers/container/container.go
api/handlers/container/top.go
api/handlers/container/top_test.go
e2e/tests/container_top.go
internal/backend/container.go
internal/service/container/top.go
internal/service/container/top_test.go
mocks/mocks_backend/nerdctlcontainersvc.go
mocks/mocks_container/containersvc.go

This PR adds Support for [Container top API](https://docs.docker.com/reference/api/engine/version/v1.43/#tag/Container/operation/ContainerTop) - The API lists the running processes inside a container
- ~needs https://github.com/containerd/nerdctl/pull/4063~ (merged)
- unit and e2e tests added
- adds a new API (GET) `container/top`
Output format
```
{
"Processes": [
[
"root",
"25508",
"25472",
"0",
"18:55",
"?",
"00:00:00",
"sleep Infinity"
]
],
"Titles": [
"UID",
"PID",
"PPID",
"C",
"STIME",
"TTY",
"TIME",
"CMD"
]
}
```

feat: Add container top support
